version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: currency_exchange
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis

  web:
    build: .
    command: flask run --host=0.0.0.0
    environment:
      FLASK_APP: app.py
      DATABASE_URL: postgresql://user:password@db:5432/currency_exchange
      OPENEXCHANGERATES_API_KEY: your_open_exchange_rates_api_key
      MAIL_USERNAME: your_email@example.com
      MAIL_PASSWORD: your_email_password
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    command: celery -A tasks worker --loglevel=info
    environment:
      FLASK_APP: app.py
      DATABASE_URL: postgresql://user:password@db:5432/currency_exchange
      OPENEXCHANGERATES_API_KEY: your_open_exchange_rates_api_key
      MAIL_USERNAME: your_email@example.com
      MAIL_PASSWORD: your_email_password
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    command: celery -A tasks beat --loglevel=info
    environment:
      FLASK_APP: app.py
      DATABASE_URL: postgresql://user:password@db:5432/currency_exchange
      OPENEXCHANGERATES_API_KEY: your_open_exchange_rates_api_key
      MAIL_USERNAME: your_email@example.com
      MAIL_PASSWORD: your_email_password
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
